config/routes.rb
Rails.application.routes.draw do
  resources :municipes, only: [:index, :new, :edit, :create]
  resources :municipios, only: [:index, :new, :edit, :create]
  resources :enderecos, only: [:new, :create, :edit]

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/municipio.rb
class Municipio < ApplicationRecord
  has_many :municipes
end

app/controllers/municipios_controller.rb
class MunicipiosController < ApplicationController
  include ApplicationHelper
  before_action :set_municipio, only: %i[ show edit update]
  respond_to :json, :html
  # GET /municipios or /municipios.json
  #
  def index

    search =''
    params_index = params.permit!
    params_to_search = params_index[:q] || {}

    to_search ={
      created_at_gteq:(Date.today - 30.days).beginning_of_day,
      created_at_lteq: Date.today.end_of_day
    }
    @rows = params_index['rows'].presence || 10
    @q = model_name.ransack(to_search)

    @items = @q.result(distinct: true).order(id: :desc)
    @items = @items.page(params[:page]).per(@rows)



  end

  # GET /municipios/1 or /municipios/1.json
  def show
  end

  # GET /municipios/new
  def new
    @municipio = Municipio.new
  end

  # GET /municipios/1/edit
  def edit
  end

  # POST /municipios or /municipios.json
  def create
    @municipio = Municipio.new(municipio_params)

    respond_to do |format|
      if @municipio.save
        format.html { redirect_to municipios_url(@municipio), notice: "Create municipio was successfully created." }
        format.json { render :show, status: :created, location: @municipio }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @municipio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /municipios/1 or /municipios/1.json
  def update
    respond_to do |format|
      if @municipio.update(municipio_params)
        format.html { redirect_to municipios_url(@municipio), notice: "Create municipio was successfully updated." }
        format.json { render :show, status: :ok, location: @municipio }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @municipio.errors, status: :unprocessable_entity }
      end
    end
  end



  private
    def model_name
      Municipio
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_municipio
      @municipio = Municipio.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def municipio_params
      params.permit(:nome)
    end
end

app/helpers/municipios_helper.rb
module MunicipiosHelper
end

app/views/municipios/_form.html.erb
<p style="color: green"><%= notice %></p>
<style>
    .input_width {
        width: 100%;
    }
</style>
<div data-controller="context" class="container mt-5">
  <div class="card card-default">
    <div class="card-body">

      <div class="row  col-xl-12">
        <div class="bg-content flex-1 col-xl-12"  style="margin-right: 24px; ">
          <div class="title">
            <div style="display: flex; justifyContent: 'space-between'">
              ADICIONAR MUNICIPIO
            </div>
          </div>
          <hr class="d-print-none">

          <%= simple_form_for(@municipio) do |f| %>
            <div class="row">

              <div class="col-12">
                <div class="form-group">
                  <label>Nome do municipio</label>
                  <input class="form-control" value="" type="text" id="nome"  name="nome" required>
                </div>
              </div>

            </div>


            <hr class="d-print-none">
            <div class="col-xl-12">
              <div class="clearfix"></div>
              <div class="box-header pt-0 pl-0 ms-0 mb-4 mt-4 border-bottom-0 responsive-header">
                <h4 class="box-title fs-22"></h4>
                <div class="card-options">
                  <%= link_to 'Voltar', municipios_path , class: 'btn btn-secondary' %>
                  <%= f.submit 'Adicionar', class: 'btn btn-primary' %>
                </div>
              </div>



            </div>
          <% end %>
        </div>
      </div>

    </div>
  </div>

</div>
<%= content_for(:vendor_js_area) do %>

<%end %>
<script>
    $(function () {
        $(document).ready(function () {
            $('.datepicker').datepicker({
                dateFormat: 'dd/mm/yy',
                dayNames: ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado'],
                dayNamesMin: ['D', 'S', 'T', 'Q', 'Q', 'S', 'S', 'D'],
                dayNamesShort: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb', 'Dom'],
                monthNames: ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
                monthNamesShort: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'],
                nextText: 'Proximo',
                prevText: 'Anterior'
            });



        });

    });

</script>

app/views/municipios/edit.html.erb
<h1>Editing Create Municipio</h1>

<%= render 'form', municipio: @municipio %>

<%= link_to 'Show', @municipio %> |
<%= link_to 'Back', municipios_path %>

app/views/municipios/index.html.erb
<p style="color: green"><%= notice %></p>
<div data-controller="context-menu" class="container mt-5">
  <div class="card card-default">
    <div class="card-body">
      <h1> Listagem de Municipios</h1>

      <hr class="d-print-none">

      <div class=" col-xl-12 float-left">
        <div class="  float-left">
          <a href="<%= new_municipio_path %>" >
            <button type="button" style="margin-top: 15px; margin-left: 15px; margin-right: 15px; " class=" btn btn-success mb-1">Novo Cadastro</button>
          </a>
        </div>
      </div>

    </div>
  </div>
  <br>
  <div class="card card-default">
    <div class="card-body">
      <%if @items.present?  %>
      <table class="table table-vcenter text-nowrap table-bordered dataTable no-footer" id="task-profile" role="grid">
        <thead>
        <tr class="top">
          <th class="border-bottom-0 text-center sorting fs-14 font-w500" tabindex="0" aria-controls="task-profile" rowspan="1" colspan="1" style="width: 26.6562px;">No</th>
          <th class="border-bottom-0 sorting fs-14 font-w500" tabindex="0" aria-controls="task-profile" rowspan="1" colspan="1" >Municipio</th>
          <th colspan="2" class="border-bottom-0 sorting fs-14 font-w500" tabindex="0" aria-controls="task-profile" rowspan="2" >Ação</th>
        </tr>
        </thead>
        <tbody>

            <% @items.each do |item|  %>
              <tr class="odd">
                <td class="text-center"><%= item.id %></td>
                <td>
                  <a  class="d-flex "> <span><%= item.nome %></span> </a>
                </td>
                <td><%= link_to 'Edit', edit_municipio_path(item) %></td>
              </tr>
            <% end %>


        </tbody>
      </table>
      <%else %>
        <div> Nenhum resultado</div>

      <% end %>
    </div>
  </div>
</div>

app/views/municipios/new.html.erb
<%= render partial: "#{controller_path}/form" %>

app/views/municipios/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_municipio_path(@municipio) %> |
<%= link_to 'Back', municipios_path %>