config/routes.rb
Rails.application.routes.draw do
  resources :municipes, only: [:index, :new, :edit, :create]
  resources :municipios, only: [:index, :new, :edit, :create]
  resources :enderecos, only: [:new, :create, :edit]

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/municipe.rb
class Municipe < ApplicationRecord

  belongs_to :municipio


  validates :nome_completo, :cpf, :cns, :email, :data_nascimento, :telefone, :foto, presence: true
  validates :cpf, cpf: true
  validates :cns, format: { with: /\A\d{15}\z/, message: "deve ter 15 dígitos" }
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validate :data_nascimento_valida
  validates :cep, :logradouro, :bairro, :cidade, :uf, presence: true
  validates :cep, format: { with: /\A\d{5}-\d{3}\z/, message: "deve estar no formato 12345-123" }
  validates :uf, length: { is: 2, message: "deve ter 2 caracteres" }
  validates :codigo_ibge, numericality: { only_integer: true, allow_blank: true }

  def data_nascimento_valida
    errors.add(:data_nascimento, "inválida") if data_nascimento.present? && data_nascimento > Date.today
  end

  has_one :endereco
  accepts_nested_attributes_for :endereco
  has_one_attached :photo do |attachable|
    attachable.variant :small, resize: "200x200"
    attachable.variant :medium, resize: "400x400"
    attachable.variant :medium, resize: "600x600"
    # Adicione mais variantes conforme necessário
  end

end

app/controllers/municipes_controller.rb
class MunicipesController < ApplicationController
  include ApplicationHelper
  before_action :set_municipe, only: %i[ show edit update]
  respond_to :json, :html
  # GET /municipes or /municipes.json

  def index

    search =''
    params_index = params.permit!
    params_to_search = params_index[:q] || {}

    to_search ={
      created_at_gteq:(Date.today - 30.days).beginning_of_day,
      created_at_lteq: Date.today.end_of_day
    }
    @rows = params_index['rows'].presence || 10
    @q = model_name.ransack(to_search)

    @items = @q.result(distinct: true).order(id: :desc)
    @items = @items.page(params[:page]).per(@rows)






  end

  # GET /municipes/1 or /municipes/1.json
  def show
  end

  # GET /municipes/new
  def new
    @municipe = Municipe.new
    @municipe.build_endereco
  end

  # GET /municipes/1/edit
  def edit
  end

  # POST /municipes or /municipes.json
  def create

    @municipe = Municipe.new

    @municipe.nome_completo = municipe_params[:nome_completo]
    @municipe.cpf = municipe_params[:cpf]
    @municipe.cns = municipe_params[:cns]
    @municipe.email = municipe_params[:email]
    @municipe.data_nascimento = municipe_params[:data_nascimento]
    @municipe.telefone = municipe_params[:telefone]
    @municipe.foto = municipe_params[:foto]
    @municipe.status = municipe_params[:status]
    @municipe.municipio_id = municipe_params[:municipio_id]

    respond_to do |format|
      if @municipe.save!(validate: false)

        @endereco = Endereco.new
        @endereco.municipe_id = @municipe.id
        @endereco.cep = endereco_params[:cep]
        @endereco.logradouro = endereco_params[:logradouro]
        @endereco.complemento = endereco_params[:complemento]
        @endereco.bairro = endereco_params[:bairro]
        @endereco.cidade = endereco_params[:cidade]
        @endereco.uf = endereco_params[:uf]
        @endereco.codigo_ibge = endereco_params[:codigo_ibge]
        @endereco.save

        # Envio de e-mail
        NotificationMailer.send_link(@municipe.email, @municipe.nome_completo, "Cadastro").deliver_now
        notification_sms = NotificationSms.new
        notification_sms.send_sms(@municipe.nome_completo, @municipe.telefone)

        format.html { redirect_to municipes_url(@municipe), notice: "Municipe criado com sucesso." }
        format.json { render :show, status: :created, location: @municipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @municipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /municipes/1 or /municipes/1.json
  def update
    @municipe.nome_completo = municipe_params[:nome_completo]
    @municipe.cpf = municipe_params[:cpf]
    @municipe.cns = municipe_params[:cns]
    @municipe.email = municipe_params[:email]
    @municipe.data_nascimento = municipe_params[:data_nascimento]
    @municipe.telefone = municipe_params[:telefone]
    @municipe.foto = municipe_params[:foto]
    @municipe.status = municipe_params[:status]

    respond_to do |format|
      if @municipe.update

        @endereco = Endereco.new
        @endereco.municipe_id = @municipe.id
        @endereco.cep = endereco_params[:cep]
        @endereco.logradouro = endereco_params[:logradouro]
        @endereco.complemento = endereco_params[:complemento]
        @endereco.bairro = endereco_params[:bairro]
        @endereco.cidade = endereco_params[:cidade]
        @endereco.uf = endereco_params[:uf]
        @endereco.codigo_ibge = endereco_params[:codigo_ibge]
        @endereco.save

          # Envio de e-mail
          NotificationMailer.send_link(@municipe.email, @municipe.nome_completo, "Cadastro").deliver_now
          notification_sms = NotificationSms.new
          notification_sms.send_sms(@municipe.nome_completo, @municipe.telefone)


        format.html { redirect_to municipes_url(@municipe), notice: "Municipe was successfully updated." }
        format.json { render :show, status: :ok, location: @municipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @municipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /municipes/1 or /municipes/1.json
  def destroy
    @municipe.destroy

    respond_to do |format|
      format.html { redirect_to municipes_url, notice: "Municipe was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def model_name
      Municipe
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_municipe
      @municipe = Municipe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def municipe_params
      params.permit(:nome_completo, :cpf, :cns, :email, :data_nascimento, :telefone, :foto,:municipio_id, :status)
    end
    def endereco_params
      params.permit(:cep, :logradouro, :complemento, :bairro, :cidade, :uf, :codigo_ibge)

    end
end

app/helpers/municipes_helper.rb
module MunicipesHelper
end

app/views/municipes/edit.html.erb
<h1>Editing Municipe</h1>

<%= render 'form', municipe: @municipe %>

<%= link_to 'Show', @municipe %> |
<%= link_to 'Back', municipes_path %>

app/views/municipes/index.html.erb
<p style="color: green"><%= notice %></p>
<div data-controller="context-menu" class="container mt-5">
  <div class="card card-default">
    <div class="card-body">
      <h1> Listagem de Municipes</h1>

      <hr class="d-print-none">

      <div class=" col-xl-12 float-left">
        <div class="  float-left">
          <a href="<%= new_municipe_path %>" >
            <button type="button" style="margin-top: 15px; margin-left: 15px; margin-right: 15px; " class=" btn btn-success mb-1">Novo Cadastro</button>
          </a>
        </div>
      </div>

    </div>
  </div>
  <br>
    <div class="card card-default">
      <div class="card-body">
        <%if @items.present?  %>
          <table class="table table-vcenter text-nowrap table-bordered dataTable no-footer" id="task-profile" role="grid">
            <thead>
            <tr class="top">
              <th class="border-bottom-0 text-center sorting fs-14 font-w500" tabindex="0" aria-controls="task-profile" rowspan="1" colspan="1" style="width: 26.6562px;">No</th>
              <th class="border-bottom-0 sorting fs-14 font-w500" tabindex="0" aria-controls="task-profile" rowspan="1" colspan="1" >nome_completo</th>
              <th class="border-bottom-0 sorting fs-14 font-w500" tabindex="0" aria-controls="task-profile" rowspan="1" colspan="1" >cpf</th>
              <th class="border-bottom-0 sorting fs-14 font-w500" tabindex="0" aria-controls="task-profile" rowspan="1" colspan="1" >email</th>
              <th class="border-bottom-0 sorting fs-14 font-w500" tabindex="0" aria-controls="task-profile" rowspan="1" colspan="1" >status</th>
              <th colspan="2" class="border-bottom-0 sorting fs-14 font-w500" tabindex="0" aria-controls="task-profile" rowspan="2" >Ação</th>
            </tr>
            </thead>
            <tbody>

            <% @items.each do |item|  %>
              <tr class="odd">
                <td class="text-center"><%= item.id %></td>
                <td>
                   <span><%= item.nome_completo %></span>
                </td>
                <td>
                   <span><%= item.cpf %></span>
                </td>
                <td>
                   <span><%= item.email %></span>
                </td>
                <td>
                    <% if item.status == true%>
                     p> Ativo</p>
                   <%else %>
                     <p> Inativo</p>
                   <%end %>
                </td>

                <td><%= link_to 'Edit', edit_municipe_path(item) %></td>
              </tr>
            <% end %>


            </tbody>
          </table>
        <%else %>
          <div> Nenhum resultado</div>

        <% end %>
      </div>
    </div>
  </div>


</div>

app/views/municipes/new.html.erb
<%= render partial: "#{controller_path}/form" %>

app/views/municipes/show.html.erb
<p id="notice"><%= notice %></p>


<% if @municipe.photo.attached? %>
  <p><%= image_tag @municipe.photo.variant(resize: "200x200") %></p> <!-- Tamanho pequeno -->
  <p><%= image_tag @municipe.photo.variant(resize: "400x400") %></p> <!-- Tamanho médio -->
  <p><%= image_tag @municipe.photo.variant(resize: "600x600") %></p> <!-- Tamanho grande -->
  <!-- Outros tamanhos de imagem aqui -->
<% end %>
<%= link_to 'Edit', edit_municipe_path(@municipe) %> |
<%= link_to 'Back', municipes_path %>