config/routes.rb
Rails.application.routes.draw do
  resources :municipes, only: [:index, :new, :edit, :create]
  resources :municipios, only: [:index, :new, :edit, :create]
  resources :enderecos, only: [:new, :create, :edit]

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/endereco.rb
class Endereco < ApplicationRecord
  belongs_to :municipe

  validates :cep, :logradouro, :bairro, :cidade, :uf, presence: true
  validates :cep, format: { with: /\A\d{5}-\d{3}\z/, message: "deve estar no formato 12345-123" }
  validates :uf, length: { is: 2, message: "deve ter 2 caracteres" }
  validates :codigo_ibge, numericality: { only_integer: true, allow_blank: true }
end

app/controllers/enderecos_controller.rb
class EnderecosController < ApplicationController
  include ApplicationHelper
  before_action :set_endereco, only: %i[ show edit update destroy ]

  # GET /enderecos or /enderecos.json
  def index
    @enderecos = Endereco.all
  end

  def show
  end

  # GET /enderecos/new
  def new
    @endereco = Endereco.new
  end

  # GET /enderecos/1/edit
  def edit
  end

  # POST /enderecos or /enderecos.json
  def create
    @endereco = Endereco.new(endereco_params)

    respond_to do |format|
      if @endereco.save
        format.html { redirect_to endereco_url(@endereco), notice: "Endereço criado com sucesso." }
        format.json { render :show, status: :created, location: @endereco }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @endereco.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enderecos/1 or /enderecos/1.json
  def update
    respond_to do |format|
      if @endereco.update(endereco_params)
        format.html { redirect_to endereco_url(@endereco), notice: "Endereco was successfully updated." }
        format.json { render :show, status: :ok, location: @endereco }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @endereco.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enderecos/1 or /enderecos/1.json
  def destroy
    @endereco.destroy

    respond_to do |format|
      format.html { redirect_to enderecos_url, notice: "Endereco was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_endereco
      @endereco = Endereco.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def endereco_params
      params.require(:endereco).permit(:cep, :logradouro, :complemento, :bairro, :cidade, :uf, :codigo_ibge)
    end
end

app/helpers/enderecos_helper.rb
module EnderecosHelper
end

app/views/enderecos/_form.html.erb
<%= form_with(model: endereco, local: true) do |form| %>
  <% if endereco.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(endereco.errors.count, "error") %> prohibited this endereco from being saved:</h2>

      <ul>
      <% endereco.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/enderecos/edit.html.erb
<h1>Editing Endereco</h1>

<%= render 'form', endereco: @endereco %>

<%= link_to 'Show', @endereco %> |
<%= link_to 'Back', enderecos_path %>

app/views/enderecos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Enderecos</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enderecos.each do |endereco| %>
      <tr>
        <td><%= link_to 'Show', endereco %></td>
        <td><%= link_to 'Edit', edit_endereco_path(endereco) %></td>
        <td><%= link_to 'Destroy', endereco, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Endereco', new_endereco_path %>

app/views/enderecos/new.html.erb
<h1>Novo Endereço</h1>
<%= form_for @endereco do |f| %>
  <div>
    <%= f.label :cep %>
    <%= f.text_field :cep %>
  </div>
  <!-- Adicione os campos restantes do Endereço aqui -->
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/enderecos/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_endereco_path(@endereco) %> |
<%= link_to 'Back', enderecos_path %>